package de.tum.bgu.msm.health.disease;

public enum Diseases {
    all_cause_cancer ,
    all_cause_cvd ,
    all_cause_dementia,
    all_cause_mortality,
    alzheimer_disease,
    bladder_cancer,
    breast_cancer,
    colon_cancer,
    coronary_heart_disease,
    depression,
    depressive_symptoms,
    diabetes,
    endometrial_cancer,
    esophageal_cancer,
    gastric_cardia_cancer,
    head_and_neck_cancer,
    heart_failure,
    kidney_cancer,
    liver_cancer,
    lung_cancer,
    major_depression,
    myeloid_leukemia,
    myeloma,
    parkinson_disease,
    prostate_cancer,
    rectum_cancer,
    stroke,
    vascular_dementia
}
