#Properties for SILO
#Legend                                                      set by user          default

#Main properties
scenario.name                                                = test
base.year                                                    = 2011
#end.year                                                     = 2021
end.year                                                     = 2013
random.seed 												 = 1
transport.model	                                             = matsim
    #transport.model = {mito_matsim, matsim} or none if no transport model is used
travel.time 												 = matsim
#matsim

transport.model.years = 2012,2015,2021




#Accessibility - skim matrices
auto.peak.sov.skim.2011              = car_0800_0900_900_car_travel_times.csv.gz
auto.peak.sov.skim.matrix.name       = timeByTime
skims.factor.car					 = 0.016667
transit.peak.time.2011               = total_t_transit.omx
transit.peak.time.matrix.name        = mat1


#jr
zones.shapefile = input/zonesShapefile/zones_Berlin-Brandenburg_size_3715_popCap_5000_crs_31468.shp
zonal.data.file = input/zonesShapefile/zones.csv

#region.definition.file   = input/regionDefinitionMunicipalityDistrict.csv

# job forecast: job.forecast.method = {"rate", "interpolation"}
# for rate, use "job.growth.rate" for a fixed growth rate across the whole study area and all sectors (in percentage)
# for interpolation, use "interpol.empl.forecast" to point to a file with fixed target values per sector and zone
# also see documentation at https://wiki.tum.de/display/msmmodels/Employment+Forecast
job.forecast.method = rate
job.growth.rate = 0.5


# population control totals: "population.control.total": {"population", "migration", "rate"}
# for rate, use "population.growth.rate" for a fixed growth rate across the whole study area (in percentage)
# for population, use "total.population.control.total.file" to point to a file with fixed target values
# for migration, use "inmigration.outmigration.file" to point to a file with fixed target in-/out migration numbers
# also see documentation at https://wiki.tum.de/display/msmmodels/Population+forecast
population.control.total = rate
population.growth.rate = 0.5

scale.factor = 0.01
#mito.properties.file = mito.properties
matsim.include.access.egress = false

